# Generated by Django 5.2.5 on 2025-09-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_options_category_category_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='affected_areas',
            field=models.TextField(default='sd', help_text='Geographic areas affected by this disaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disaster',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
    ]
